webapp/app/models.py
from app import db
from datetime import datetime

class MyTable(db.Model):
    id    = db.Column(db.Integer, primary_key=True)
    item  = db.Column(db.String(32))
    value = db.Column(db.Float)
    stamp = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
         return '{}: {} = {} at {}'.format(self.id, self.item, self.value, self.stamp)

webapp/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, EqualTo, Length, NumberRange


class MyTable_Form(FlaskForm):
    item = StringField('Item', validators=[DataRequired()])
    value = StringField('Value', validators=[DataRequired()])
    submit = SubmitField('Record')

webapp/app/__init__.py
from flask import Flask, current_app
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)


    with app.app_context():

        db.init_app(app)
        migrate.init_app(app, db)

        from app.main import bp as main_bp
        app.register_blueprint(main_bp)

        from app.api import bp as api_bp
        app.register_blueprint(api_bp, url_prefix='/api')

        from app.main.boot import OnBoot, cyclic_task, sayhello

        if app.config['START_FLAG'] == "True":
            OnBoot()
            cyclic_task(sayhello)
            
        return app


from app import models

webapp/app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import data

webapp/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes, boot

webapp/app/main/routes.py
from flask import current_app, render_template, redirect, url_for, request
import random, logging

from app import db
from app.main import bp
from app.models import *
from app.main.forms import MyTable_Form
from app.main.boot import *

@bp.route('/')
@bp.route('/index', methods=['GET', 'POST'])
def index():

    mytableform = MyTable_Form()

    templateData = {
        'title' : 'Working With Docker',
        'section' : 'Running Docker Containers',
        'loc_var_01' : current_app.config['LOC_VAR_01'],
        'app_version' : current_app.config['APP_VERSION'],
        'mytable_rows' : MyTable.query.all(),
        'form' : mytableform
    }

    if request.method == 'POST':
     
        button = request.form.get('button')
        if button == 'add2db':
            new_row = MyTable(item=f'newdata_{MyTable.query.count()+1}', value=random.uniform(0, 10))
            db.session.add(new_row)
            db.session.commit()
            
        elif button == 'erasedb':
            data = MyTable.query.all()
            for i in data:
                db.session.delete(i)
            db.session.commit()

        elif button == 'submit':
            item = request.form.get('item')
            value = request.form.get('value')
            
            logging.debug(item)
            logging.debug(value)
            
            new_row = MyTable(item=mytableform.item.data, value=float(mytableform.value.data))
            db.session.add(new_row)
            db.session.commit()


        templateData = {
            'mytable_rows' : MyTable.query.all()
        }

        
        return render_template('index_mytable.html', **templateData)
    
    return render_template('index.html', **templateData)

@bp.route('/media', methods=['GET', 'POST'])
def media():

    templateData = {
        'title' : 'Another Page',
        'section' : 'It\'s great!',
        'loc_var_01' : current_app.config['LOC_VAR_01'],
        'app_version' : current_app.config['APP_VERSION']
    }

    return render_template('media.html', **templateData)

webapp/app/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no">
    
    <link rel="stylesheet" media="screen" href="{{url_for('static', filename='css/project.css')}}">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>    
      
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            Title Not Set
        {% endif %}
    </title>
    
    {% block head %}
    {% endblock %}

</head>

<body>  

    {% block navbar %}
    {% endblock %}        

    {% block content %}
    {% endblock %}    

    {% block scripts %}  
    <script>
    </script>
    {% endblock %} 

</body>
</html>

webapp/app/templates/index.html
{% extends "base.html" %}

{% block head %}
<style>

</style>
{% endblock %}

{% block content %}

<div  id=MyPage>
    <h1>{{ title }}</h1>
    <h3> Section: {{ section }}</h3>
    <a href="{{ url_for('main.index') }}">Home</a>
    <a href="{{ url_for('main.media') }}">Media</a>
    <hr>
    <p> Reading .env file: {{ loc_var_01 }} </p>
    <p> App Version: {{ app_version }} </p>

    
    <div id=MyForm>
        <form id="submit_form">
            {{ form.hidden_tag() }}
            <div>
                <label> {{ form.item.label }} </label>
                <p id="theItem" class="form_field">{{ form.item }}</p>
            </div>

            <div>
                <label> {{ form.value.label }} </label>
                <p id="theValue" class="form_field">{{ form.value }}</p>  
            </div>
            <button id="submit" type="submit"> Save </button>
        </form>
    </div>
    <div id="MyPanel">
    <button id="add2db" class="my_btn" style="float: right;"> + </button>
    <button id="erasedb" class="my_btn" style="float: left;"> &times </button>
    </div>
    <div id=MyTable>
    <table>
        <thead>
          <tr>
              <th>Id</th>
              <th>Item</th>
              <th>Value</th>
              <th>Time</th>
          </tr>
        </thead>
        <tbody>
          {% for row in mytable_rows %}
          <tr>
              <th>{{ row.id }}</th>
              <td>{{ row.item }}</td> 
              <td>{{ row.value }}</td>
              <td>{{ (row.stamp).strftime("%b %d %Y %H:%M:%S") }}</td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
    </div>
    
</div>

<script>

$('#submit_form').on('submit', function(e){
    e.preventDefault();

    var form = $('#submit_form')[0];
    var data = new FormData(form)

    data.append('button', 'submit')

    req = $.ajax({
        type : 'POST',
        url : '/index',
        data : data,
        contentType: false,
        processData: false, 
        success : function(){
        }
    });
    req.done(function(data) {
      $('#MyTable').html(data);
    });
});


$('#add2db').on('click', function(){
    req = $.ajax({
        type : 'POST',
        url : '/index',
        data : { button : 'add2db'}, 
        success : function(){
        }
    });
    req.done(function(data) {
      $('#MyTable').html(data);
    });
});

$('#erasedb').on('click', function(){
    req = $.ajax({
        type : 'POST',
        url : '/index',
        data : { button : 'erasedb'}, 
        success : function(){
        }
    });
    req.done(function(data) {
      $('#MyTable').html(data);
    });
});

</script>

{% endblock %}

webapp/app/templates/index_mytable.html
<table>
    <thead>
      <tr>
          <th>Id</th>
          <th>Item</th>
          <th>Value</th>
          <th>Time</th>
      </tr>
    </thead>
    <tbody>
      {% for row in mytable_rows %}
      <tr>
          <th>{{ row.id }}</th>
          <td>{{ row.item }}</td> 
          <td>{{ row.value }}</td>
          <td>{{ '{:%m/%d/%Y %H:%M:%S}'.format(row.stamp)}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

webapp/app/templates/media.html
{% extends "base.html" %}

{% block head %}
<style>

</style>
{% endblock %}

{% block content %}

<div  id=MyPage>
    <h1>{{ title }}</h1>
    <h3>{{ section }}</h3>
    <a href="{{ url_for('main.index') }}">Home</a>
    <hr>
    <p> Reading .env file: {{ loc_var_01 }} </p>
    <p> App Version: {{ app_version }} </p>
  
</div>

<script>

</script>

{% endblock %}